6 completely rework readme
Danilado/jaba-is-you pull request #11
Opened 2024-05-22 21:05 UTC by Danilado

#6

2024-05-22 21:48 UTC, quswadress requested changes, later dismissed

2024-05-22 21:48 UTC, quswadress commented on README.md
> +# The final project for the "Industrial Programming" course of [MSHP](https://informatics.ru)
I would make a separate Russian translation of the readme and move this disclaimer there. Nobody outside Moscow and its districts needs this disclaimer. Mention that this is a training project is already written below.

2024-05-22 21:48 UTC, quswadress commented on README.md
> +We don't take any credit on creating the game idea and /or mechanics. This is a project created for educational purposes with consent of original game's creator (Hempuli) through an email
```suggestion
We don't take any credit for creating the game's idea, mechanics, sprites, and/or music. This is a project created for educational purposes with the consent of the original game's creator ([Hempuli](https://www.hempuli.com/)) via email.
```

2024-05-23 11:47 UTC, Danilado reviewed
done
https://github.com/Danilado/jaba-is-you/pull/11/commits/5b6f2ae5e1d668011abbc01f305547527f821ec3

2024-05-23 12:30 UTC, quswadress approved these changes
Looks good, _at least adequate_. :-)

2024-05-23 12:38 UTC, merged